### PR TITLE
Add Oulipo::Validators::StatusValidator

### PR DESCRIPTION
**Pull request by ecmendenhall**
Fix for #10 

- Yank `FIFTH_GLYPH_R*G*X` up from `Oulipo::Formatt*r`
- Do Status validation via Activ\*R\*cord validator
- Add Oulipo i18n strings
- Add Activ\*R\*cord i18n strings

Q for you, @mouse-reeve: I don't know that I grasp local vs nonlocal toots...do toots from "Global activity" also go in our DB as local toots? If so, this might blow up, as global toots should allow invalid glyphs, but local toots should not. If not, this is OK.

### CODE REVIEW

**Comment by ecmendenhall** [comment]
(It should only apply validation to local toots, thanks to this `status.local?` bit)

**Comment by ecmendenhall** [comment]
Bah, a TODO: this should also apply validation to `spoil*r_t*xt`, a distinct column on `Status`.

**Comment by ecmendenhall** [comment]
OK, now it's good.

**Comment by mouse-reeve** [comment]
Looks like there's a merge conflict, but I'm happy to merge this in otherwise

**Comment by ecmendenhall** [comment]
Thanks, can't look right now, but I'll patch it up tonight!

**Comment by ecmendenhall** [comment]
Good now! I'm thinking of a way to fix automatic trials from Mastodon's main branch: put our invalid glyphs in config, and modify that in `RAILS_*NV=test`. I'll do a distinct PR for it.

**Comment by ecmendenhall** [comment]
I am not good at this without that magic box.

**Pull request merged**
